import { getAIModelSettings, isProviderEnabled } from '../../config/aiModelConfig';
import { coerceProviderId, getProviderLabel } from '../../config/providerCatalog';
import type { AIProvider } from '../../types/template';
import { AIProviderError } from './errors';
import { resolvePromptByExactId, resolvePromptByRuntimeId } from '../promptService';
import { assemblePrompt, assembleRawPrompt, JSON_ONLY_SYSTEM_PROMPT, type AssembledPrompt, type PromptRef } from './promptAssembly';
import { getAdapter } from './registry';
import { recordCompletion, recordFailure } from './telemetry';
import {
  createDeadline,
  isEffortLevel,
  type CompletionRequest,
  type CompletionResponseFormat,
  type CompletionResult,
  type EffortLevel,
} from './types';

/**
 * The one entry point every AI call in this app goes through.
 *
 * `claude-cli` is the default because the app's premise is a subscription seat
 * rather than metered tokens. This constant matters more than it looks: two
 * callers (profile extraction and template extraction) pass no provider at all,
 * so a default left pointing at a metered provider would keep billing for them
 * with nothing in the UI to say so.
 */
export const DEFAULT_PROVIDER: AIProvider = 'claude-cli';

/** Fallback wall-clock budget when a caller names none. */
const DEFAULT_TIMEOUT_MS = 300_000;

export type PromptExecutionConfig = {
  provider: AIProvider;
  modelName?: string;
};

/**
 * Which provider and model a prompt runs on: the prompt record's own override
 * when it has one, otherwise what the caller asked for.
 */
export async function resolvePromptExecutionConfig(
  promptId: string,
  fallbackProvider: AIProvider,
  fallbackModelName?: string,
  useExactPromptId = false
): Promise<PromptExecutionConfig> {
  const prompt = useExactPromptId
    ? await resolvePromptByExactId(promptId)
    : await resolvePromptByRuntimeId(promptId);

  return configFromRecord(prompt, fallbackProvider, fallbackModelName);
}

function configFromRecord(
  record: { modelProvider?: AIProvider; modelName?: string } | null,
  fallbackProvider: AIProvider,
  fallbackModelName?: string
): PromptExecutionConfig {
  const provider = coerceProviderId(record?.modelProvider);
  if (!provider || !record?.modelName) {
    return { provider: fallbackProvider, modelName: fallbackModelName };
  }
  return { provider, modelName: record.modelName };
}

export type CreatePromptCompletionInput = {
  promptId: string;
  /**
   * Values for the prompt's `[[variables]]`. The prompt is rendered here, once,
   * from these - callers no longer render it themselves and pass the text.
   */
  promptValues: Record<string, string>;
  fallbackProvider?: AIProvider;
  fallbackModelName?: string;
  maxTokens?: number;
  temperature?: number;
  responseFormat?: CompletionResponseFormat;
  useExactPromptId?: boolean;
  /**
   * Extra instruction appended to the assembled prompt's user turn. For text
   * that must reach the model but does not belong in the stored record.
   */
  appendToUserBody?: string;
  /**
   * A JSON Schema the provider may enforce natively.
   *
   * Only pass this when the schema is GENERATED BY CODE and the prompt is not
   * one of the admin-editable prompt features. Binding a schema to a prompt an
   * admin can edit converts a recoverable "unparseable text" - which
   * `extractJSON` handles - into a hard transport failure that points at the
   * wrong layer the moment the two drift apart.
   */
  jsonSchema?: Readonly<Record<string, unknown>>;
  effort?: EffortLevel;
  timeoutMs?: number;
  signal?: AbortSignal;
};

async function runAssembled(
  assembled: AssembledPrompt,
  config: PromptExecutionConfig,
  input: {
    callSite: string;
    responseFormat: CompletionResponseFormat;
    maxTokens?: number;
    temperature?: number;
    jsonSchema?: Readonly<Record<string, unknown>>;
    effort?: EffortLevel;
    timeoutMs?: number;
    signal?: AbortSignal;
    appendToUserBody?: string;
  }
): Promise<CompletionResult> {
  const settings = await getAIModelSettings();
  if (!isProviderEnabled(config.provider, settings)) {
    throw new AIProviderError({
      provider: config.provider,
      kind: 'disabled',
      detail: `Provider "${getProviderLabel(config.provider)}" is disabled by an administrator`,
    });
  }

  const adapter = getAdapter(config.provider);
  const modelName = config.modelName || adapter.defaultModelName();

  const userBody = input.appendToUserBody
    ? `${assembled.userBody}\n\n${input.appendToUserBody}`
    : assembled.userBody;

  // A provider with no system channel gets everything in one turn, so no
  // instruction is silently dropped for it. The previous flat Anthropic path
  // dropped the JSON-only instruction entirely, which is why the one caller
  // that used it had no JSON enforcement at all.
  const foldSystem = !adapter.capabilities.systemBlocks;
  const volatileSystem = input.responseFormat === 'json' ? JSON_ONLY_SYSTEM_PROMPT : '';

  const request: CompletionRequest = {
    modelName,
    stableSystem: foldSystem ? '' : assembled.stableSystem,
    volatileSystem: foldSystem ? '' : volatileSystem,
    userBody: foldSystem
      ? [volatileSystem, assembled.stableSystem, userBody].filter(Boolean).join('\n\n')
      : userBody,
    responseFormat: input.responseFormat,
    // A schema only reaches a provider that can enforce one natively.
    jsonSchema: adapter.capabilities.nativeJsonMode === 'json-schema' ? input.jsonSchema : undefined,
    // Sampling hints are passed through UNFILTERED and on purpose. The adapter
    // owns the decision, because only it can report what it had to drop;
    // stripping them here would make the loss invisible again.
    sampling: {
      maxOutputTokens: input.maxTokens,
      temperature: input.temperature,
    },
    effort: isEffortLevel(input.effort) ? input.effort : undefined,
    deadline: createDeadline(input.timeoutMs ?? DEFAULT_TIMEOUT_MS),
    signal: input.signal,
    callSite: input.callSite,
  };

  try {
    const result = await adapter.complete(request);
    recordCompletion(input.callSite, result);
    return result;
  } catch (error) {
    recordFailure(input.callSite, config.provider, modelName);
    throw error;
  }
}

/**
 * Renders a stored prompt and runs it on the resolved provider.
 */
export async function createPromptCompletion(input: CreatePromptCompletionInput): Promise<string> {
  const ref: PromptRef = {
    id: input.promptId,
    mode: input.useExactPromptId ? 'exact' : 'runtime',
  };

  const assembled = await assemblePrompt(ref, input.promptValues);
  const config = configFromRecord(
    assembled.record,
    input.fallbackProvider || DEFAULT_PROVIDER,
    input.fallbackModelName
  );

  const result = await runAssembled(assembled, config, {
    callSite: input.promptId,
    responseFormat: input.responseFormat ?? 'json',
    maxTokens: input.maxTokens,
    temperature: input.temperature,
    jsonSchema: input.jsonSchema,
    effort: input.effort,
    timeoutMs: input.timeoutMs,
    signal: input.signal,
    appendToUserBody: input.appendToUserBody,
  });

  return result.text;
}

export type CreateRawCompletionInput = {
  callSite: string;
  system: string;
  user: string;
  provider?: AIProvider;
  modelName?: string;
  responseFormat?: CompletionResponseFormat;
  maxTokens?: number;
  temperature?: number;
  jsonSchema?: Readonly<Record<string, unknown>>;
  effort?: EffortLevel;
  timeoutMs?: number;
  signal?: AbortSignal;
};

/**
 * Runs a prompt the caller composed itself, for the bid assistant - the one
 * subsystem whose prompt template lives outside the prompt store.
 */
export async function createRawCompletion(input: CreateRawCompletionInput): Promise<string> {
  const assembled = assembleRawPrompt({ system: input.system, user: input.user });
  const result = await runAssembled(
    assembled,
    { provider: input.provider || DEFAULT_PROVIDER, modelName: input.modelName },
    {
      callSite: input.callSite,
      responseFormat: input.responseFormat ?? 'json',
      maxTokens: input.maxTokens,
      temperature: input.temperature,
      jsonSchema: input.jsonSchema,
      effort: input.effort,
      timeoutMs: input.timeoutMs,
      signal: input.signal,
    }
  );
  return result.text;
}
