import {
  getAIModelSettings,
  getDefaultEnabledProvider,
  isProviderEnabled,
  resolveRequestedAIModel,
} from '../../config/aiModelConfig';
import { aiRequestTimeoutMs } from '../../config/operational';
import {
  coerceProviderId,
  getProviderLabel,
  getProviderLockReason,
  isProviderLocked,
} from '../../config/providerCatalog';
import type { AIProvider } from '../../types/template';
import { AIProviderError } from './errors';
import { resolvePromptByExactId, resolvePromptByRuntimeId } from '../promptService';
import { assemblePrompt, assembleRawPrompt, JSON_ONLY_SYSTEM_PROMPT,
  JSON_SENTINEL_SYSTEM_PROMPT, type AssembledPrompt, type PromptRef } from './promptAssembly';
import { getAdapter } from './registry';
import { pickProvider } from './providerPool';
import { recordCompletion, recordFailure, warnOnce } from './telemetry';
import {
  createDeadline,
  type CompletionRequest,
  type CompletionResponseFormat,
  type CompletionResult,
} from './types';

/**
 * The one entry point every AI call in this app goes through.
 *
 * `claude-cli` is the provider a call that names none starts from. Two callers
 * (profile extraction and template extraction) pass no provider at all, and
 * when an administrator has switched this seat off or the deployment locks it,
 * such a call is rerouted rather than failed - see `runAssembled`.
 */
export const DEFAULT_PROVIDER: AIProvider = 'claude-cli';

export type PromptExecutionConfig = {
  provider: AIProvider;
  modelName?: string;
  /**
   * True when a prompt record or a caller named this provider on purpose.
   * False when it is only the default, in which case an admin disabling it
   * should reroute rather than fail - there is no UI for the bid assistant to
   * pick a provider, so a hard failure would leave it unusable with no way
   * back.
   */
  explicit?: boolean;
};

/**
 * Which provider and model a prompt runs on: the prompt record's own override
 * when it has one, otherwise what the caller asked for.
 */
export async function resolvePromptExecutionConfig(
  promptId: string,
  fallbackProvider: AIProvider,
  fallbackModelName?: string,
  useExactPromptId = false
): Promise<PromptExecutionConfig> {
  const prompt = useExactPromptId
    ? await resolvePromptByExactId(promptId)
    : await resolvePromptByRuntimeId(promptId);

  return configFromRecord(prompt, fallbackProvider, fallbackModelName);
}

function configFromRecord(
  record: { modelProvider?: AIProvider; modelName?: string } | null,
  fallbackProvider: AIProvider,
  fallbackModelName?: string,
  explicitFallback = true
): PromptExecutionConfig {
  const provider = coerceProviderId(record?.modelProvider);
  if (!provider || !record?.modelName) {
    return {
      provider: fallbackProvider,
      modelName: fallbackModelName,
      explicit: explicitFallback,
    };
  }

  // An override naming a provider this installation cannot run is read as no
  // override at all. It is a value STORED on the prompt record, possibly long
  // ago - so honouring it here would mean a build that locks that seat cannot
  // run any of those prompts, and the person hitting it has no way to see why
  // from the prompt they are using.
  if (isProviderLocked(provider)) {
    warnOnce(
      `lockedPromptOverride:${provider}`,
      `A prompt record names the locked provider "${getProviderLabel(provider)}"; that override is ` +
        'being ignored and those prompts run on the model chosen in the UI instead. Clear it under ' +
        'Admin -> Prompts to silence this.'
    );
    return {
      provider: fallbackProvider,
      modelName: fallbackModelName,
      explicit: explicitFallback,
    };
  }

  return { provider, modelName: record.modelName, explicit: true };
}

export type CreatePromptCompletionInput = {
  promptId: string;
  /**
   * Stable id of the calling FEATURE, for timeouts and usage buckets.
   *
   * Distinct from `promptId`, which is a prompt-record id and can be a custom
   * per-profile record. Keying the tailor-resume timeout on the record id
   * meant a profile with a custom prompt silently got the default budget.
   */
  callSite?: string;
  /**
   * Values for the prompt's `[[variables]]`. The prompt is rendered here, once,
   * from these - callers no longer render it themselves and pass the text.
   */
  promptValues: Record<string, string>;
  fallbackProvider?: AIProvider;
  fallbackModelName?: string;
  maxTokens?: number;
  temperature?: number;
  responseFormat?: CompletionResponseFormat;
  useExactPromptId?: boolean;
  /**
   * Extra instruction appended to the assembled prompt's user turn. For text
   * that must reach the model but does not belong in the stored record.
   */
  appendToUserBody?: string;
  /**
   * A JSON Schema the provider may enforce natively.
   *
   * Only pass this when the schema is GENERATED BY CODE and the prompt is not
   * one of the admin-editable prompt features. Binding a schema to a prompt an
   * admin can edit converts a recoverable "unparseable text" - which
   * `extractJSON` handles - into a hard transport failure that points at the
   * wrong layer the moment the two drift apart.
   */
  jsonSchema?: Readonly<Record<string, unknown>>;
  timeoutMs?: number;
  signal?: AbortSignal;
  /**
   * The caller's model is the one this run was priced and charged at - a
   * resume's analysis, tailoring and cover letter - so the prompt record's own
   * override does NOT replace it. Otherwise an override would run the work on
   * one model while the account paid for another, and the person's choice of
   * model would do nothing. Calls nobody pays per use of (the job filter, the
   * Bid Assistant, the extractors) leave this off and keep the override.
   */
  runChoiceWins?: boolean;
};

async function runAssembled(
  assembled: AssembledPrompt,
  config: PromptExecutionConfig,
  input: {
    callSite: string;
    responseFormat: CompletionResponseFormat;
    maxTokens?: number;
    temperature?: number;
    jsonSchema?: Readonly<Record<string, unknown>>;
      timeoutMs?: number;
    signal?: AbortSignal;
    appendToUserBody?: string;
  }
): Promise<CompletionResult> {
  const settings = await getAIModelSettings();
  let provider = config.provider;
  // The model a reroute runs on, when it lands on the app's default model
  // rather than on a provider's own default. See below.
  let reroutedModelName: string | undefined;

  if (!isProviderEnabled(provider, settings)) {
    const lockReason = getProviderLockReason(provider);
    if (lockReason && config.explicit !== false) {
      // Reported as its own kind so the message names the real obstacle. A
      // locked provider is not something an administrator can switch back on.
      throw new AIProviderError({
        provider,
        kind: 'locked',
        detail: `Provider "${getProviderLabel(provider)}" is locked in this installation`,
        adminAction: lockReason,
      });
    }
    if (config.explicit !== false) {
      throw new AIProviderError({
        provider,
        kind: 'disabled',
        detail: `Provider "${getProviderLabel(provider)}" is disabled by an administrator`,
      });
    }
    // Nobody chose this provider - it was only the default. Reroute rather
    // than fail, so a caller with no provider setting of its own does not
    // become unusable the moment an admin unticks a box.
    //
    // Onto the app's default MODEL first - the one the settings page shows and
    // every other call that names nothing runs on - so the reroute lands where
    // an administrator pointed the install rather than on whichever seat sorts
    // first in the catalog. Only when that cannot run does it take the first
    // enabled seat, on the seat's own default model.
    let alternative: AIProvider | undefined;
    const fallback = await resolveRequestedAIModel().catch(() => null);
    if (fallback && isProviderEnabled(fallback.provider, settings)) {
      alternative = fallback.provider;
      reroutedModelName = fallback.modelName;
    }
    alternative ??= getDefaultEnabledProvider(settings);
    if (!isProviderEnabled(alternative, settings)) {
      throw new AIProviderError({
        provider,
        kind: 'disabled',
        detail: 'No AI provider is enabled',
      });
    }
    warnOnce(
      `reroute:${provider}->${alternative}`,
      `The default provider "${getProviderLabel(provider)}" is disabled; calls that name no provider ` +
        `are running on "${getProviderLabel(alternative)}" instead.`
    );
    provider = alternative;
  }

  const userBody = input.appendToUserBody
    ? `${assembled.userBody}\n\n${input.appendToUserBody}`
    : assembled.userBody;

  // Which provider of the type answers (owner decision P4): the one a queued
  // task holds a lane slot on, else the readiest with the most free capacity.
  // The model and its price are the type's; only where it runs is chosen here.
  // Picked for the model the call names, when it names one ('' is the type's
  // default), so a provider held for that model alone is passed over.
  const namedModel = (config.explicit && config.modelName) || reroutedModelName || '';
  const adapter = getAdapter(pickProvider(provider, namedModel)?.id ?? provider);
  const modelName = namedModel || adapter.defaultModelName();

  // A provider with no system channel gets everything in one turn, so no
  // instruction is silently dropped for it. The previous flat Anthropic path
  // dropped the JSON-only instruction entirely, which is why the one caller
  // that used it had no JSON enforcement at all.
  const foldSystem = !adapter.capabilities.systemBlocks;
  // Which JSON instruction, decided by what the TRANSPORT can enforce.
  //
  // A provider with a native JSON mode is already constrained and needs only
  // to be told not to narrate; asking it for sentinels would put them inside
  // the JSON it is obliged to emit and break the one output that was
  // guaranteed to parse. A transport with no JSON mode enforces nothing, so it
  // gets the long instruction and the sentinels the extractor keys on.
  const volatileSystem =
    input.responseFormat === 'json'
      ? adapter.capabilities.nativeJsonMode === 'none'
        ? JSON_SENTINEL_SYSTEM_PROMPT
        : JSON_ONLY_SYSTEM_PROMPT
      : '';

  const request: CompletionRequest = {
    modelName,
    stableSystem: foldSystem ? '' : assembled.stableSystem,
    volatileSystem: foldSystem ? '' : volatileSystem,
    userBody: foldSystem
      ? [volatileSystem, assembled.stableSystem, userBody].filter(Boolean).join('\n\n')
      : userBody,
    responseFormat: input.responseFormat,
    // A schema only reaches a provider that can enforce one natively.
    jsonSchema:
      adapter.capabilities.nativeJsonMode === 'json-schema' ? input.jsonSchema : undefined,
    // Sampling hints are passed through UNFILTERED and on purpose. The
    // adapter owns the decision, because only it can report what it had to
    // drop; stripping them here would make the loss invisible again.
    sampling: {
      maxOutputTokens: input.maxTokens,
      temperature: input.temperature,
    },
    // AI_REQUEST_TIMEOUT_MS, read per call. No caller passes `timeoutMs`
    // today, so in practice this IS the deadline of every AI call - which is
    // why it is a setting: a slow seat or a long tailoring prompt needs more
    // than five minutes on some installs and nothing in the code could say
    // which. It bounds the wait for a seat's slot and the CLI child (the
    // smaller of this and the call site's AI_CLI_TIMEOUT_MS* /
    // AI_CODEX_TIMEOUT_MS* wins, and startup warns when one of those is set
    // above this).
    deadline: createDeadline(input.timeoutMs ?? aiRequestTimeoutMs()),
    signal: input.signal,
    callSite: input.callSite,
  };

  try {
    const result = await adapter.complete(request);
    recordCompletion(input.callSite, modelName, result);
    return result;
  } catch (error) {
    recordFailure(input.callSite, provider, modelName);
    throw error;
  }
}

/**
 * Renders a stored prompt and runs it on the resolved provider.
 */
export async function createPromptCompletion(input: CreatePromptCompletionInput): Promise<string> {
  return (await createPromptCompletionResult(input)).text;
}

/**
 * The same call, answering the whole result - for a caller that must know more
 * than the text: the tailoring cache keeps an answer only when the model it
 * asked for wrote it (`fellBack`).
 */
export async function createPromptCompletionResult(input: CreatePromptCompletionInput): Promise<CompletionResult> {
  const ref: PromptRef = {
    id: input.promptId,
    mode: input.useExactPromptId ? 'exact' : 'runtime',
  };

  const assembled = await assemblePrompt(ref, input.promptValues);
  const config: PromptExecutionConfig =
    input.runChoiceWins && input.fallbackProvider
      ? { provider: input.fallbackProvider, modelName: input.fallbackModelName, explicit: true }
      : configFromRecord(
          assembled.record,
          input.fallbackProvider || DEFAULT_PROVIDER,
          input.fallbackModelName,
          // A caller that named a provider chose it; one that fell through to
          // the default did not, and should be rerouted rather than failed if
          // an admin has disabled that default.
          Boolean(input.fallbackProvider)
        );

  const result = await runAssembled(assembled, config, {
    callSite: input.callSite || input.promptId,
    responseFormat: input.responseFormat ?? 'json',
    maxTokens: input.maxTokens,
    temperature: input.temperature,
    jsonSchema: input.jsonSchema,
    timeoutMs: input.timeoutMs,
    signal: input.signal,
    appendToUserBody: input.appendToUserBody,
  });

  return result;
}

export type CreateRawCompletionInput = {
  callSite: string;
  system: string;
  user: string;
  provider?: AIProvider;
  modelName?: string;
  responseFormat?: CompletionResponseFormat;
  maxTokens?: number;
  temperature?: number;
  jsonSchema?: Readonly<Record<string, unknown>>;
  timeoutMs?: number;
  signal?: AbortSignal;
};

/**
 * Runs a prompt the caller composed itself, for the bid assistant - the one
 * subsystem whose prompt template lives outside the prompt store.
 */
export async function createRawCompletion(input: CreateRawCompletionInput): Promise<string> {
  const assembled = assembleRawPrompt({ system: input.system, user: input.user });
  const result = await runAssembled(
    assembled,
    {
      provider: input.provider || DEFAULT_PROVIDER,
      modelName: input.modelName,
      // The bid assistant passes the app default model it resolved, which is a
      // choice; a caller that names no provider gets the default instead, and
      // is rerouted rather than failed when an admin has switched it off.
      explicit: Boolean(input.provider),
    },
    {
      callSite: input.callSite,
      responseFormat: input.responseFormat ?? 'json',
      maxTokens: input.maxTokens,
      temperature: input.temperature,
      jsonSchema: input.jsonSchema,
        timeoutMs: input.timeoutMs,
      signal: input.signal,
    }
  );
  return result.text;
}
