import type { AIProvider } from '../../types/template';

/**
 * Contracts for the AI transport layer.
 *
 * This module has NO runtime imports beyond a type-only one: no SQLite, no
 * dotenv, no child_process, and no side effects at load. That is what lets the
 * provider tests run hermetically, and a test asserts it.
 */

export type CompletionResponseFormat = 'json' | 'text';

/** A knob a caller asked for that the chosen provider cannot honour. */
export type DroppedParam = 'temperature' | 'maxOutputTokens' | 'jsonSchema';

/**
 * Sampling values the CALLER would like. They are hints, not guarantees:
 * consult `ProviderCapabilities` before assuming one was applied, and read
 * `CompletionResult.droppedParams` afterwards to find out what was not.
 */
export type SamplingHints = {
  readonly maxOutputTokens?: number;
  readonly temperature?: number;
};

/**
 * A wall-clock budget for one completion, shared by every layer that can wait:
 * the concurrency semaphore and the subprocess.
 */
export interface Deadline {
  readonly totalMs: number;
  remainingMs(): number;
  expired(): boolean;
}

export function createDeadline(totalMs: number, now: () => number = Date.now): Deadline {
  const startedAt = now();
  const budget = Math.max(1, Math.round(totalMs));
  return {
    totalMs: budget,
    remainingMs() {
      return Math.max(0, budget - (now() - startedAt));
    },
    expired() {
      return now() - startedAt >= budget;
    },
  };
}

export type CompletionRequest = {
  readonly modelName: string;
  /**
   * System text that is byte-stable for a given prompt: the literal preamble
   * before the first `[[variable]]`. Kept separate from the user body because
   * that is the shape a CLI's own system-prompt channel wants, and because it
   * keeps per-call data out of the instruction channel.
   */
  readonly stableSystem: string;
  /** System text that varies with the call, e.g. the JSON-only instruction. */
  readonly volatileSystem: string;
  /** The user turn: rendered variables and everything after the first one. */
  readonly userBody: string;
  readonly responseFormat: CompletionResponseFormat;
  /**
   * A JSON Schema the provider may enforce natively.
   *
   * Only set this when the schema is GENERATED BY CODE and the prompt is not
   * one of the admin-editable prompt features. A schema pinned to a prompt an
   * admin can edit turns a recoverable "unparseable text" into a hard
   * transport failure the moment the two drift apart.
   */
  readonly jsonSchema?: Readonly<Record<string, unknown>>;
  readonly sampling: SamplingHints;
  readonly deadline: Deadline;
  readonly signal?: AbortSignal;
  /** Stable id of the calling feature, for logs and usage buckets. */
  readonly callSite: string;
};

export type CompletionUsage = {
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly cacheReadTokens: number;
  readonly cacheWriteTokens: number;
};

export type CompletionResult = {
  /**
   * The answer. NEVER partial: a turn cut off by the clock or by the model's
   * output limit throws instead of returning what arrived. Returning a
   * fragment is worse than failing here, because `extractJSON` will happily
   * find a balanced sub-object inside a truncated document and hand it to a
   * parser that then blames the prompt.
   */
  readonly text: string;
  readonly resolvedModel: string;
  /**
   * True when the seat says a model other than the one asked for answered:
   * Claude's `--fallback-model` taking an overloaded model's turn, Gemini
   * switching Pro to Flash. The answer is used as it is; what it must not be
   * is KEPT as the asked-for model's - the tailoring cache would otherwise
   * hand a fallback's answer to every repeat, at the asked-for model's price.
   * Absent means no seat said so.
   */
  readonly fellBack?: boolean;
  /** The provider TYPE (the seat's kind), which is what a price and a model name belong to. */
  readonly providerId: AIProvider;
  /**
   * Which provider of that type answered (config/aiProviders.ts): its type id
   * for the built-in one, `prv-...` for one an administrator added. For the
   * log and the admin pages; nothing about a run's price depends on it.
   */
  readonly providerInstanceId?: string;
  readonly usage?: CompletionUsage;
  /** Notional on a subscription seat: a measure of work, not an invoice. */
  readonly costUsd?: number;
  readonly droppedParams: readonly DroppedParam[];
  readonly latencyMs: number;
};

export type ProviderCapabilities = {
  readonly id: AIProvider;
  readonly label: string;
  readonly temperature: boolean;
  readonly maxOutputTokens: boolean;
  readonly nativeJsonMode: 'json-schema' | 'none';
  /** false => the facade folds system text into the head of the user body. */
  readonly systemBlocks: boolean;
  /** Simultaneous in-flight calls this provider tolerates. */
  readonly maxConcurrency: number;
};

export type ProviderHealth = {
  readonly ok: boolean;
  readonly detail: string;
  readonly checkedAt: string;
  /**
   * The CLI's own word for its sign-in, where it reports one: `claude auth
   * status`'s authMethod, or the Gemini seat's `oauth-personal`. Whether a
   * Claude one is the subscription is claudeCli/health.ts's
   * `isSubscriptionSignIn` - `claude.ai` or `oauth_token`, with no API key
   * named beside it - never this field compared alone.
   */
  readonly authMethod?: string | null;
  /** A non-fatal problem an operator should still see (e.g. key-based auth). */
  readonly warning?: string;
  readonly meta?: Readonly<Record<string, unknown>>;
};

/**
 * One provider of a type, as its adapter is built (owner decision P1): where
 * its sign-in lives, which binary it runs and how many calls it takes at once.
 *
 * The built-in provider of each type has the type's id and reads `.env` for
 * whatever an administrator has not set; every other one was added on
 * Admin -> Models with a folder of its own. Resolved by config/aiProviders.ts;
 * declared here so the adapters take it without importing configuration.
 */
export type ProviderInstanceSpec = {
  /** The provider's id: the type id for the built-in one, `prv-<8 hex>` for an added one. */
  readonly id: string;
  readonly label: string;
  readonly builtIn: boolean;
  /**
   * The sign-in/config folder the child is given (CLAUDE_CONFIG_DIR, CODEX_HOME
   * or GEMINI_CLI_HOME). Null leaves the CLI's own default - the service
   * user's home, or whatever the server's environment already says.
   */
  readonly homeDir: string | null;
  readonly binaryPath: string;
  /** concurrency_max_requests: the provider's own limit, its semaphore and its queue lane. */
  readonly concurrency: number;
};

/**
 * What a provider's adapter knows, synchronously, about whether it can take a
 * call now - read by the queue's dispatcher and by the pool that spreads a
 * type's calls over its providers (owner decision P4), neither of which may
 * wait on a health check.
 */
export type ProviderReadiness = {
  /**
   * The last health check's verdict: true signed in and runnable, false
   * signed out or missing, null when nothing has been checked yet - which
   * counts as ready, so a provider is never benched on a guess.
   */
  readonly ready: boolean | null;
  /**
   * A hold that would turn the call away, while it lasts: on the whole seat,
   * or - when `readiness` was asked about a model - on that model. A weekly
   * Opus cap holds Opus only, so a provider under one still takes Sonnet
   * work, and asked about no model (the admin card) it reads as not held.
   */
  readonly held: { readonly kind: string; readonly reason: string; readonly until: string } | null;
};

export type HealthOptions = {
  /** Ask the CLI again even when a check from the last minute is cached. */
  readonly fresh?: boolean;
};

export interface AIProviderAdapter {
  /** The provider TYPE. Two Claude providers are both `claude-cli`. */
  readonly id: AIProvider;
  /**
   * Which provider of the type this adapter is: absent on a test's stub,
   * which stands in for every provider of its type.
   */
  readonly instanceId?: string;
  readonly capabilities: ProviderCapabilities;
  /** The model used when neither the prompt nor the caller names one. */
  defaultModelName(): string;
  /**
   * Cheap, cached, never billable, never throws. Boot preflight + admin UI.
   * `fresh` skips the cache: the admin Settings page asks for it, because a
   * fresh check that finds a seat signed in is what lifts its sign-in hold.
   */
  health(options?: HealthOptions): Promise<ProviderHealth>;
  /** Rejects with AIProviderError - never a bare Error. Honours the deadline. */
  complete(request: CompletionRequest): Promise<CompletionResult>;
  /**
   * Cheap and synchronous: the last health verdict and any hold on the seat -
   * and, given a model name (as a caller would send it; '' for the default),
   * any hold on that model too, so the queue and the pool never place a
   * model's work on a provider that would turn it away unasked. Optional, so
   * a stub without one reads as always ready.
   */
  readiness?(modelName?: string): ProviderReadiness;
}
